version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:    
    image: php:8-fpm
    build: 
      context: .docker/php/.
    volumes:
      - ./:/var/www/html
 